# This is a basic workflow to help you get started with Actions

name: SFDX-Example-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [synchronize, ready_for_review ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run-pmd 
        uses: sfdx-actions/setup-pmd@v1
      - run: |
          # pmd -d . -r ${{env.PMD_RULESET_FILE}} -format text -reportfile ${{env.PMD_RESULTS_FILE}} -failOnViolation false -no-cache
          pmd -d . -R pmd-apex-ruleset.xml -f text -r pmd.xml -failOnViolation false -no-cache
          if [ -s "pmd.xml" ] # if the size of the file is more than 0 then...
          then
            cat pmd.xml
            numberOfViolations=$(grep "" -c pmd.xml) # counting number of lines, as the result file has error per line
            echo "Apex code analysis found $numberOfViolations violations" 
            exit 0 # Make it exit 1 when we want this to fail the build
          fi

